### ISSUE TITLE
Ember compatibility?

### ISSUE THREAD

**Issue by davewasmer** [bakerac4/glimmer-native#11]
This is a super exciting project - thanks for the great work @bakerac4!

Just wondering what the plans are (if any) around Ember integration (i.e. ember-native). Would this project be a stepping stone in that direction?

**Comment by bakerac4** [comment]
@davewasmer I have put some thought into that, but Im just concentrating on getting Glimmer Native solidified. I think what I would like to see is the pattern that ember.js itself is moving to. 

They are trying to make it so you can use 1 or many parts of the current ember.js and just pick and choose what you need. So in my ideal world if you needed an extremely simple app you would just use Glimmer Native. If you needed something a bit more complex you would then import Glimmer NativeRouter/Glimmer NativeRoutes etc. There are also some other major issues that would need to be improved/solved like the build system. 

Either way, I think its on the roadmap but without major help it won't be coming for awhile.
