### ISSUE TITLE
nativescript-windows-android issue

### ISSUE THREAD

**Issue by lifeart** [bakerac4/glimmer-native#2]
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Error calling module function 

Error calling module function 

Error: Cannot find module './undefined/component.ts'
File: "file:///data/data/org.nativescript.demo/files/app/bundle.js, line: 21, column: 2

StackTrace: 
	Frame: function:'webpackContextResolve', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 19, column: 11
	Frame: function:'webpackContext', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 13, column: 11
	Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 156, column: 113
	Frame: function:'addComponents', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 154, column: 28
	Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 161, column: 1
	Frame: function:'./app.ts', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 175, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.demo/files/app/runtime.js', line: 75, column: 30
	Frame: function:'checkDeferredModules', file:'file:///data/data/org.nativescript.demo/files/app/runtime.js', line: 44, column: 23
	Frame: function:'webpackJsonpCallback', file:'file:///data/data/org.nativescript.demo/files/app/runtime.js', line: 31, column: 19
	Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 2, column: 57
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/starter.js', line: 3, column: 1
	Frame: function:'require', file:'', line: 1, column: 266

Error: Cannot find module './undefined/component.ts'
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'webpackContextResolve', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 19, column: 11
	Frame: function:'webpackContext', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 13, column: 11
	Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 156, column: 113
	Frame: function:'addComponents', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 154, column: 28
	Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 161, column: 1
	Frame: function:'./app.ts', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 175, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.demo/files/app/runtime.js', line: 75, column: 30
	Frame: function:'checkDeferredModules', file:'file:///data/data/org.nativescript.demo/files/app/runtime.js', line: 44, column: 23
	Frame: function:'webpackJsonpCallback', file:'file:///data/data/org.nativescript.demo/files/app/runtime.js', line: 31, column: 19
	Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 2, column: 57
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/starter.js', line: 3, column: 1
	Frame: function:'require', file:'', line: 1, column: 266

Error: Cannot find module './undefined/component.ts'
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'webpackContextResolve', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 19, column: 11
	Frame: function:'webpackContext', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 13, column: 11
	Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 156, column: 113
	Frame: function:'addComponents', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 154, column: 28
	Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 161, column: 1
	Frame: function:'./app.ts', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 175, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.demo/files/app/runtime.js', line: 75, column: 30
	Frame: function:'checkDeferredModules', file:'file:///data/data/org.nativescript.demo/files/app/runtime.js', line: 44, column: 23
	Frame: function:'webpackJsonpCallback', file:'file:///data/data/org.nativescript.demo/files/app/runtime.js', line: 31, column: 19
	Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 2, column: 57
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/starter.js', line: 3, column: 1
	Frame: function:'require', file:'', line: 1, column: 266

	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5406)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: com.tns.NativeScriptException: 

Error calling module function 

Error calling module function 

Error: Cannot find module './undefined/component.ts'
File: "file:///data/data/org.nativescript.demo/files/app/bundle.js, line: 21, column: 2

StackTrace: 
	Frame: function:'webpackContextResolve', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 19, column: 11
	Frame: function:'webpackContext', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 13, column: 11
	Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 156, column: 113
	Frame: function:'addComponents', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 154, column: 28
	Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 161, column: 1
	Frame: function:'./app.ts', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 175, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.demo/files/app/runtime.js', line: 75, column: 30
	Frame: function:'checkDeferredModules', file:'file:///data/data/org.nativescript.demo/files/app/runtime.js', line: 44, column: 23
	Frame: function:'webpackJsonpCallback', file:'file:///data/data/org.nativescript.demo/files/app/runtime.js', line: 31, column: 19
	Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 2, column: 57
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/starter.js', line: 3, column: 1
	Frame: function:'require', file:'', line: 1, column: 266

Error: Cannot find module './undefined/component.ts'
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'webpackContextResolve', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 19, column: 11
	Frame: function:'webpackContext', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 13, column: 11
	Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 156, column: 113
	Frame: function:'addComponents', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 154, column: 28
	Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 161, column: 1
	Frame: function:'./app.ts', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 175, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.demo/files/app/runtime.js', line: 75, column: 30
	Frame: function:'checkDeferredModules', file:'file:///data/data/org.nativescript.demo/files/app/runtime.js', line: 44, column: 23
	Frame: function:'webpackJsonpCallback', file:'file:///data/data/org.nativescript.demo/files/app/runtime.js', line: 31, column: 19
	Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 2, column: 57
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/starter.js', line: 3, column: 1
	Frame: function:'require', file:'', line: 1, column: 266

Error: Cannot find module './undefined/component.ts'
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'webpackContextResolve', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 19, column: 11
	Frame: function:'webpackContext', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 13, column: 11
	Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 156, column: 113
	Frame: function:'addComponents', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 154, column: 28
	Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 161, column: 1
	Frame: function:'./app.ts', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 175, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.demo/files/app/runtime.js', line: 75, column: 30
	Frame: function:'checkDeferredModules', file:'file:///data/data/org.nativescript.demo/files/app/runtime.js', line: 44, column: 23
	Frame: function:'webpackJsonpCallback', file:'file:///data/data/org.nativescript.demo/files/app/runtime.js', line: 31, column: 19
	Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/bundle.js', line: 2, column: 57
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/starter.js', line: 3, column: 1
	Frame: function:'require', file:'', line: 1, column: 266

	at com.tns.Runtime.runModule(Native Method)
	at com.tns.Runtime.runModule(Runtime.java:624)
	at com.tns.Runtime.run(Runtime.java:616)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
	... 8 more

**Comment by lifeart** [comment]
![image](https://user-images.githubusercontent.com/1360552/58986261-b7a7d180-87e5-11e9-9989-de822ad9550e.png)

looks like `components.json` does not have name for component

**Comment by lifeart** [comment]
`componentLocation C:\Users\lifeart\Documents\repos\hello-glimmer-native\platforms\android\app\src\main\assets\app\src\ui\components\HelloGlimmerNative\component.ts` 

so `const nameArray = componentLocation.split("/");` won't work for this case

**Comment by bakerac4** [comment]
Fixed. Thanks for the PR @lifeart
