### ISSUE TITLE
#each having trouble with longer list

### ISSUE THREAD

**Issue by CodingItWrong** [bakerac4/glimmer-native#9]
Reproduction project: https://github.com/CodingItWrong/todo-glimmer-native

I'm outputting an array with `#each`:

```
    @tracked
    todos = [
      'Try Glimmer Native',
      'Make a Sample App',
      'Make a Tutorial',
    ]
```

```
  <StackLayout>
...
    {{#each todos as |todo|}}
      <Label text={{todo}} />
    {{/each}}
  </StackLayout>
```

<img width="394" alt="Screen Shot 2019-06-20 at 9 25 18 AM" src="https://user-images.githubusercontent.com/15832198/59852750-7cf17d80-933d-11e9-9cac-bb74ca3570c4.png">

I have two actions that update the array:

```
    replaceTodos() {
      this.todos = ['1', '2', '3']
    }

    replaceWithLongerArray() {
      this.todos = ['A', 'B', 'C', 'D', 'E']
    }
```

When I `replaceTodos` with an array of the same length they display fine:

<img width="316" alt="Screen Shot 2019-06-20 at 9 26 36 AM" src="https://user-images.githubusercontent.com/15832198/59852764-84188b80-933d-11e9-8835-eaecda5189a7.png">

But when I replace with a longer list, the same number of items show, and the very last item is layered over the bottommost from the original array length:

<img width="313" alt="Screen Shot 2019-06-20 at 9 27 08 AM" src="https://user-images.githubusercontent.com/15832198/59852838-aca08580-933d-11e9-925b-7e1fde78cf9e.png">

Might the layout not be reflowing, so that all the items longer than the initial length overlap one another?

**Comment by lifeart** [comment]
@CodingItWrong try specify key for each and use objects, instead of strings

**Comment by CodingItWrong** [comment]
That definitely fixed it!

It might be good for there to be a warning in the logs when there's an `#each` without a key. Thoughts?

I'll do a PR to update the `#each` example in the readme to include a key.

**Comment by bakerac4** [comment]
@CodingItWrong I'll update the docs in that branch I'm using. Regarding a warning in the logs, I think thats a great idea. But that would be in glimmer.js/glimmer vm itself. Closing this for now, as a new version of Glimmer Native is being released shortly with the document change fix
